### ISSUE TITLE
freestyle expression might be unnecessary

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy-garden/garden.animationbuilder#1]
This is not an actual issue, but more like suggestion. Sorry I don't know where should I write this.

### Reason 1: freestyle expression is always substitutable with another method

For example:

```yaml
test:
  freestyle: "(anim1 + anim2) & (sleep(2) + anim3)"
```

is equivalent to

```yaml
test:
  P:
    - S: [anim1, anim2]
    - S: [{d: 2}, anim3]
```

which is equivalent to

```yaml
test:
  P:
    - S:
      - anim1
      - anim2
    - S:
      - d: 2
      - anim3
```

I don't know which one is better.

### Reason 2: reducing code

`BinOp(), Add(), BitAnd(), Expr(), Name(), Call(), Call_sleep(), compile_node()`

These methods are only used by "freestyle expression"

### I myself couldn't decide how should do about this.
