### ISSUE TITLE
This module is not convenient as mush as I initially thought

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy-garden/garden.animationbuilder#2]
Mainly because

## Accessing through `locals` and `globals` is annoying

Instead of writing like this:

```python3
anims = AnimationBuilder.load_string('...')
anims.globals['some_attr'] = 'some_value' 
anims.locals['some_attr2'] = 'some_value2' 
```

wanna write like this:

```python3
anims = AnimationBuilder.load_string('...')
anims['some_attr'] = 'some_value' 
anims['some_attr2'] = 'some_value2' 
```

I probabely should hide `locals` and `globals` from users.

## The place of `repeat` attribute, I feel it's weird

```yaml
shake_anim:
  repeat: True
  sequence:
    - right: 30
      d: .5
    - left: 30
      d: .5
```

Since `repeat` is a attribute of `kivy.animation.Sequence` I wanna write like this:

```yaml
shake_anim:
  sequence:
    repeat: True
    - right: 30
      d: .5
    - left: 30
      d: .5
```

But this produce syntax error.

## ~~Prefixes are annoying~~(already fixed)

Instead of writing like this:

```yaml
change_color:
  color: "eval: get_random_color()"
  d: "eval: random() + additional_time"
```

wanna write like this:

```yaml
change_color:
  color: "get_random_color()"
  d: "random() + additional_time"
```
